# #################################
#
# IMPORTANT: If you make any changes to this file, you must also update
# couchbase-server-black-duck-manifest.yaml in this directory!
#
# #################################

# Extra dependencies that are unique to Unix (Linux or MacOS)
dependencies:
  - libffi=3.3
  - ncurses=6.2
